# Generated by Django 2.0 on 2017-12-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
    ]
