# Generated by Django 2.0 on 2017-12-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
    ]
