# Generated by Django 2.0 on 2017-12-29 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=16)),
                ('priority', models.PositiveSmallIntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')])),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Doctor')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Clinic')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Patient')),
            ],
        ),
    ]
