# Generated by Django 2.0 on 2018-01-03 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_clinictickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmacyTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField()),
                ('medicines', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=16)),
                ('priority', models.PositiveSmallIntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')])),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Patient')),
                ('referrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='LabTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField()),
                ('test', models.TextField()),
                ('result', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=16)),
                ('priority', models.PositiveSmallIntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')])),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Lab')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Patient')),
                ('referrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('note', models.TextField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Patient')),
            ],
        ),
    ]
