# Generated by Django 2.0 on 2018-01-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_farmacytickets_labtickets_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=128),
        ),
    ]
